### ISSUE TITLE
Docker hub build

### ISSUE THREAD

**Issue by celianvdb** [PyPlanet/docker#3]
Hi,
IDK if it's supposed to be auto or not but I noticed that since the 0.7.0, build are not triggered when there is a new release of pyplanet.

https://hub.docker.com/r/pyplanet/controller/tags

**Comment by tomvlk** [comment]
It’s a manual progress :) and I forgot it. 
I will make a post build action for this in Travis I think

**Comment by tomvlk** [comment]
Correction, I might want to move the Dockerfile to the main repo for this ;)

**Comment by celianvdb** [comment]
So, this repo is doomed to disappear ?

**Comment by tomvlk** [comment]
Not sure yet @celianvdb . I need to think about it first. And I want your opinion as well.

**Comment by celianvdb** [comment]
I was hesitating to ask you if you wanted to integrate the docker part on the main repo some hours ago ^^ So I think the best is to don't use this repo and work directly on the main one.
It will be cleaner and easier to maintain.

**Comment by tomvlk** [comment]
Going to use the main PyPlanet/PyPlanet repo.
