### ISSUE TITLE
Docker : Multi Container (pool default) or 1 Container (multi pool) ?

### ISSUE THREAD

**Issue by jocio** [PyPlanet/docker#4]
Hello,

I have severale dedicated server on my server, each one is a container with his own port (see my docker-compose below).
I can add a pyplanet with 1 pool but when I am trying to add several pools, it is not working anymore. What am I missing ? Thanks by advance for the help.

`version: "3"`
`networks:`
`    server-network:`
`        external:`
`            name: traefik_server-network`

`services:`
`    maniaplanet_pimserver1:`
`        container_name: maniaplanet_pimserver1`
`        build: .`
`        restart: always`
`        env_file: ./dedicated_vars.maniaplanet_pimserver1.env`
`        volumes:`
`            - ./UserData:/dedicated/UserData`
`            - ./Logs/maniaplanet_pimserver1:/dedicated/Logs`
`        expose: # visible only by the other containers (not the internet)`
`            - 5001`
`        ports: # visible by everyone (especially the internet)`
`            - 2351:2351`
`            - 2351:2351/udp`
`            - 3451:3451`
`            - 3451:3451/udp`
`        networks:`
`            - server-network`
`    maniaplanet_pimserver2:`
`        container_name: maniaplanet_pimserver2`
`        build: .`
`        restart: always`
`        env_file: ./dedicated_vars.maniaplanet_pimserver2.env`
`        volumes:`
`            - ./UserData:/dedicated/UserData`
`            - ./Logs/maniaplanet_pimserver2:/dedicated/Logs`
`        expose: # visible only by the other containers (not the internet)`
`            - 5002`
`        ports: # visible by everyone (especially the internet)`
`            - 2352:2352`
`            - 2352:2352/udp`
`            - 3452:3452`
`            - 3452:3452/udp`
`        networks:`
`            - server-network`

`    maniaplanet_pyplanet:`
`        container_name: maniaplanet_pyplanet`
`        image: pyplanet/controller`
`        build: pyplanet`
`        restart: always`
`        env_file: ./dedicated_vars.maniaplanet_pimserver1.env`
`        depends_on:`
`            - maniaplanet_pimserver1`
`        volumes:`
`            - ./pyplanet/server:/app/server`
`            - ./UserData:/dedicated/UserData`
`        networks:`
`            - server-network`

**Comment by celianvdb** [comment]
If it can help you ;) https://github.com/PyPlanet/PyPlanet/pull/874/files

**Comment by jocio** [comment]
Thank you for your quick response 👍 but there is only **one couple** of dedicated server + controller.
My concern is know what I need to do to have multiple dedicated server with pyplanet on each of them.

**Comment by celianvdb** [comment]
So, you have two choices: docker swarm ( maybe oversized, IDK your need but you can take a look ) or ``docker-compose -p SERVERNAME`` it will change the prefix of containers, networks and volumes started with the dockercompose file, it should fix your problems.

**Comment by jocio** [comment]
Thank you for your help but I am not sure that it will solve my problem, I will try to resume it below.
When I execute the command `docker-compose up -d` (See below my `docker-compose.yml` file), I have 3 containers with the 2 dedicated servers + the pyplanet controller.
I exept to have the pyplanet working for both of the dedicated server but it is not working.
I think I have missunderstood **what is a pool for pyplanet**, have I ?

My `base.py` file contain 2 pools :
> Add your pools (the controller instances per dedicated here) or leave as it is to use a single instance only.
> POOLS = [
> 	'py_pool_server_01',
> 	'py_pool_server_02',
> ]
> ... Every others block in double (py_pool_server_01 + py_pool_server_02)
> DEDICATED = {
> 	'py_pool_server_01': {
> 		'HOST': 'maniaplanet_server_01',
> 		'PORT': '5001',
> 		'USER': 'SuperAdmin',
> 		'PASSWORD': 'my_secret_password',
> 	},
> 	'py_pool_server_02': {
> 		'HOST': 'maniaplanet_server_02',
> 		'PORT': '5002',
> 		'USER': 'SuperAdmin',
> 		'PASSWORD': 'my_secret_password',
> 	},
> }
> ... Every others block in double for each pool (py_pool_server_01 + py_pool_server_02)

My `docker-compose.yml` file :
> version: "3"
> 
> services:
>     controller_pyplanet:
>         container_name: controller_pyplanet
>         image: pyplanet/controller
>         restart: always
>         env_file: ./dedicated_vars.maniaplanet_server_01.env
>         depends_on:
>             - maniaplanet_server01
>             - maniaplanet_server02
>         volumes:
>             - ./UserData:/dedicated/UserData
>             - ./pyplanet/server:/app/server
> 
>     maniaplanet_server_01:
>         container_name: maniaplanet_server_01
>         image: PyPlanet/maniaplanet-docker
>         restart: always
>         env_file: ./dedicated_vars.maniaplanet_server_01.env
>         volumes:
>             - ./UserData:/dedicated/UserData
>             - ./Logs/maniaplanet_server_01:/dedicated/Logs
>         expose: # visible only by the other containers (not the internet)
>             - 5001
>         ports: # visible by everyone (especially the internet)
>             - 2351:2351
>             - 2351:2351/udp
>             - 3451:3451
>             - 3451:3451/udp
> 
>     maniaplanet_server_02:
>         container_name: maniaplanet_server_02
>         image: PyPlanet/maniaplanet-docker
>         restart: always
>         env_file: ./dedicated_vars.maniaplanet_server_02.env
>         volumes:
>             - ./UserData:/dedicated/UserData
>             - ./Logs/maniaplanet_server_02:/dedicated/Logs
>         expose: # visible only by the other containers (not the internet)
>             - 5002
>         ports: # visible by everyone (especially the internet)
>             - 2352:2352
>             - 2352:2352/udp
>             - 3452:3452
>             - 3452:3452/udp

**Comment by celianvdb** [comment]
Oh, sorry I misunderstand the problem, I was thinking that it was supposed to be totaly separate serer. I never used pyplanet controller for multiple maniplanet server. 
@tomvlk maybe have a solution

**Comment by celianvdb** [comment]
I just noticed that you are using port 5001 in the docker compose for the first maniaplanet server but in the pylanet config it's 5007.

And second problem, maniaplanet server is still listening on default port.

You must use 
5001:5000 in your docker compose file.
And same for the others ports of course.

**Comment by jocio** [comment]
> I just noticed that you are using port 5001 in the docker compose for the first maniaplanet server but in the pylanet config it's 5007.
> 
> And second problem, maniaplanet server is still listening on default port.
> 
> You must use
> 5001:5000 in your docker compose file.
> And same for the others ports of course.

My bad, I have actually 8 servers ... that's why I have copy/paste by mistake a "5007" value :)

If y use 5001:5000 + 2351:2350 ... and 5002:5000 +2352:2350 ...
In the base.py, I have to put the same ports for each of my server ?

**Comment by jocio** [comment]
I have retried and it is not ok : my problem was to map the volume "/app/server" in my docker-compose. The container can't write in it
After that, I had some "duplicates" in my apps.py ... I have to comment "pyplanet.apps.core.statistics"

Thank you @celianvdb for your help anyway :)

One last question : do you know how to change automaticaly at the start of the server the value of **S_TimeLimit** (default 300 seconds = 5 minutes) ?

**Comment by tomvlk** [comment]
@jocio @celianvdb thanks for helping him out here. Indeed, every server should have their own docker-compose/docker environment. The pools is not supported inside the Docker environment, and is against the design of Docker itself of course.

We will soon revamp the whole docker setup so we can run everything more easily and it get's updated faster as well.

**Comment by celianvdb** [comment]
So, concretly, you have two solutions : first one, write a docker-compose with 8 controller and 8 maniaplanet. ( and database if you need it )
Seconde one ( better one ): use one of these soutions https://github.com/PyPlanet/docker/issues/4#issuecomment-616201198

**Comment by jocio** [comment]
Thank you, I have used 1 controller to rule the 8 servers.
The base.py contain the 8 pools and it is woring fine in the docker container, I take it :)
